<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
    <PackageReference Include="Npgsql" Version="10.0.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Polly" Version="8.6.6" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="OpenAI" Version="2.10.0" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="YoutubeExplode" Version="6.6.0" />
  </ItemGroup>

</Project>
