using DeckFlow.Core.Storage;
using Dapper;

namespace DeckFlow.Core.Content;

/// <summary>
/// Default implementation of <see cref="ILlmSpendLedger"/> backed by the local Content KB database.
/// </summary>
public sealed class LlmSpendLedger : SpendLedgerBase, ILlmSpendLedger
{
    // Why: gpt-4o-mini pricing confirmed 2026-05-27 per platform.openai.com (A1).
    private const decimal Gpt4oMiniInputUsdPerMillion = 0.15m;
    private const decimal Gpt4oMiniOutputUsdPerMillion = 0.60m;
    private const decimal TokensPerMillion = 1_000_000m;

    /// <summary>
    /// Creates a SQLite-backed spend ledger using the file at <paramref name="databasePath"/>.
    /// </summary>
    /// <param name="databasePath">Path to the SQLite file.</param>
    /// <param name="configurationValueResolver">Optional configuration value resolver for the monthly spend cap.</param>
    public LlmSpendLedger(string databasePath, Func<string, string?>? configurationValueResolver = null)
        : this(RelationalDatabaseConnection.FromSqlitePath(databasePath), configurationValueResolver) { }

    /// <summary>
    /// Creates a spend ledger using the supplied <see cref="RelationalDatabaseConnection"/>.
    /// </summary>
    /// <param name="connectionInfo">Provider + connection string descriptor.</param>
    /// <param name="configurationValueResolver">Optional configuration value resolver for the monthly spend cap.</param>
    public LlmSpendLedger(RelationalDatabaseConnection connectionInfo, Func<string, string?>? configurationValueResolver = null)
        : base(connectionInfo, configurationValueResolver) { }

    /// <inheritdoc />
    protected override string TableName => "llm_spend_ledger";

    /// <inheritdoc />
    protected override string MonthlyCapConfigurationKey => "DECKFLOW_LLM_MONTHLY_CAP_USD";

    /// <inheritdoc />
    public async Task RecordCallAsync(
        long videoId,
        int inputTokens,
        int outputTokens,
        decimal costUsd,
        string monthKey,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(videoId, 1);
        ArgumentOutOfRangeException.ThrowIfNegative(inputTokens);
        ArgumentOutOfRangeException.ThrowIfNegative(outputTokens);
        ArgumentOutOfRangeException.ThrowIfNegative(costUsd);
        ArgumentException.ThrowIfNullOrWhiteSpace(monthKey);
        await EnsureSchemaAsync(cancellationToken).ConfigureAwait(false);

        await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await connection.ExecuteAsync(new CommandDefinition(
            """
            INSERT INTO llm_spend_ledger (
              video_id,
              input_tokens,
              output_tokens,
              cost_usd,
              month_key,
              created_utc)
            VALUES (
              @videoId,
              @inputTokens,
              @outputTokens,
              @costUsd,
              @monthKey,
              @createdUtc);
            """,
            new
            {
                videoId,
                inputTokens,
                outputTokens,
                costUsd,
                monthKey,
                createdUtc = DateTimeOffset.UtcNow
            },
            cancellationToken: cancellationToken)).ConfigureAwait(false);
    }

    /// <summary>
    /// Computes the exact USD cost for billed gpt-4o-mini token usage.
    /// </summary>
    /// <param name="inputTokens">Exact input token count from the completion usage payload.</param>
    /// <param name="outputTokens">Exact output token count from the completion usage payload.</param>
    /// <returns>USD cost for the exact token counts.</returns>
    public static decimal ComputeCostUsd(int inputTokens, int outputTokens)
    {
        ArgumentOutOfRangeException.ThrowIfNegative(inputTokens);
        ArgumentOutOfRangeException.ThrowIfNegative(outputTokens);

        return inputTokens / TokensPerMillion * Gpt4oMiniInputUsdPerMillion
            + outputTokens / TokensPerMillion * Gpt4oMiniOutputUsdPerMillion;
    }

    /// <inheritdoc />
    protected override string PostgresCreateTableSql => """
        CREATE TABLE IF NOT EXISTS llm_spend_ledger (
          id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          video_id      BIGINT NOT NULL REFERENCES content_videos(id) ON DELETE CASCADE,
          input_tokens  INT NOT NULL,
          output_tokens INT NOT NULL,
          cost_usd      DECIMAL(10,6) NOT NULL,
          month_key     TEXT NOT NULL,
          created_utc   TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS ix_llm_spend_month ON llm_spend_ledger(month_key);
        """;

    /// <inheritdoc />
    protected override string SqliteCreateTableSql => """
        CREATE TABLE IF NOT EXISTS llm_spend_ledger (
          id            INTEGER PRIMARY KEY AUTOINCREMENT,
          video_id      INTEGER NOT NULL REFERENCES content_videos(id) ON DELETE CASCADE,
          input_tokens  INTEGER NOT NULL,
          output_tokens INTEGER NOT NULL,
          cost_usd      TEXT NOT NULL,
          month_key     TEXT NOT NULL,
          created_utc   TEXT NOT NULL DEFAULT (datetime('now'))
        );
        CREATE INDEX IF NOT EXISTS ix_llm_spend_month ON llm_spend_ledger(month_key);
        """;
}
