using DeckFlow.Core.Storage;

namespace DeckFlow.Core.Content;

/// <summary>
/// Default implementation of <see cref="IWhisperSpendLedger"/> backed by the local Content KB database.
/// </summary>
public sealed class WhisperSpendLedger : SpendLedgerBase, IWhisperSpendLedger
{
    /// <summary>
    /// Creates a SQLite-backed spend ledger using the file at <paramref name="databasePath"/>.
    /// </summary>
    /// <param name="databasePath">Path to the SQLite file.</param>
    /// <param name="configurationValueResolver">Optional configuration value resolver for the monthly spend cap.</param>
    public WhisperSpendLedger(string databasePath, Func<string, string?>? configurationValueResolver = null)
        : this(RelationalDatabaseConnection.FromSqlitePath(databasePath), configurationValueResolver) { }

    /// <summary>
    /// Creates a spend ledger using the supplied <see cref="RelationalDatabaseConnection"/>.
    /// </summary>
    /// <param name="connectionInfo">Provider + connection string descriptor.</param>
    /// <param name="configurationValueResolver">Optional configuration value resolver for the monthly spend cap.</param>
    public WhisperSpendLedger(RelationalDatabaseConnection connectionInfo, Func<string, string?>? configurationValueResolver = null)
        : base(connectionInfo, configurationValueResolver) { }

    /// <inheritdoc />
    protected override string TableName => "whisper_spend_ledger";

    /// <inheritdoc />
    protected override string MonthlyCapConfigurationKey => "DECKFLOW_WHISPER_MONTHLY_CAP_USD";

    /// <inheritdoc />
    public async Task RecordCallAsync(
        long videoId,
        int secondsBilled,
        decimal costUsd,
        string monthKey,
        CancellationToken cancellationToken = default)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(videoId, 1);
        ArgumentOutOfRangeException.ThrowIfNegative(secondsBilled);
        ArgumentOutOfRangeException.ThrowIfNegative(costUsd);
        ArgumentException.ThrowIfNullOrWhiteSpace(monthKey);
        await EnsureSchemaAsync(cancellationToken).ConfigureAwait(false);

        await using var connection = await OpenConnectionAsync(cancellationToken).ConfigureAwait(false);
        await using var command = connection.CreateCommand();
        command.CommandText = """
            INSERT INTO whisper_spend_ledger (
              video_id,
              seconds_billed,
              cost_usd,
              month_key,
              created_utc)
            VALUES (
              @videoId,
              @secondsBilled,
              @costUsd,
              @monthKey,
              @createdUtc);
            """;
        RelationalDatabaseConnection.AddParameter(command, "@videoId", videoId);
        RelationalDatabaseConnection.AddParameter(command, "@secondsBilled", secondsBilled);
        RelationalDatabaseConnection.AddParameter(command, "@costUsd", FormatDecimal(costUsd));
        RelationalDatabaseConnection.AddParameter(command, "@monthKey", monthKey);
        RelationalDatabaseConnection.AddParameter(command, "@createdUtc", FormatTimestamp(DateTimeOffset.UtcNow));
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }

    /// <inheritdoc />
    protected override string PostgresCreateTableSql => """
        CREATE TABLE IF NOT EXISTS whisper_spend_ledger (
          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          video_id       BIGINT NOT NULL REFERENCES content_videos(id) ON DELETE CASCADE,
          seconds_billed INT NOT NULL,
          cost_usd       DECIMAL(10,6) NOT NULL,
          month_key      TEXT NOT NULL,
          created_utc    TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX IF NOT EXISTS ix_spend_month ON whisper_spend_ledger(month_key);
        """;

    /// <inheritdoc />
    protected override string SqliteCreateTableSql => """
        CREATE TABLE IF NOT EXISTS whisper_spend_ledger (
          id             INTEGER PRIMARY KEY AUTOINCREMENT,
          video_id       INTEGER NOT NULL REFERENCES content_videos(id) ON DELETE CASCADE,
          seconds_billed INTEGER NOT NULL,
          cost_usd       TEXT NOT NULL,
          month_key      TEXT NOT NULL,
          created_utc    TEXT NOT NULL DEFAULT (datetime('now'))
        );
        CREATE INDEX IF NOT EXISTS ix_spend_month ON whisper_spend_ledger(month_key);
        """;
}
