namespace DeckFlow.Core.Storage;

/// <summary>
/// Postgres-specific SQL fragments and column type definitions for the DeckFlow relational schema.
/// </summary>
public sealed class PostgresRelationalDialect : IRelationalDialect
{
    /// <summary>Shared reusable singleton instance of the Postgres dialect.</summary>
    public static readonly PostgresRelationalDialect Instance = new();

    private PostgresRelationalDialect()
    {
    }

    /// <inheritdoc />
    public string SurrogateIdColumnType => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
}
