namespace DeckFlow.Core.Storage;

public sealed class PostgresRelationalDialect : IRelationalDialect
{
    public static readonly PostgresRelationalDialect Instance = new();

    private PostgresRelationalDialect()
    {
    }

    public string ParameterPrefix => "@";
    public string FeedbackIdColumnType => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    public string FeedbackCreatedUtcColumnType => "TIMESTAMPTZ";
    public string FeedbackOrderByClause => "created_utc DESC, id DESC";
    public string FeedbackInsertReturningIdSql => """
        INSERT INTO feedback (created_utc, type, message, email, page_url, user_agent, ip_hash, app_version, status)
        VALUES (@created, @type, @message, @email, @pageUrl, @userAgent, @ipHash, @appVersion, @status)
        RETURNING id;
        """;
}
