namespace DeckFlow.Core.Storage;

/// <summary>
/// Postgres-specific SQL fragments and column type definitions for the DeckFlow relational schema.
/// </summary>
public sealed class PostgresRelationalDialect : IRelationalDialect
{
    public static readonly PostgresRelationalDialect Instance = new();

    private PostgresRelationalDialect()
    {
    }

    /// <inheritdoc />
    public string SurrogateIdColumnType => "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
    /// <inheritdoc />
    public string FeedbackCreatedUtcColumnType => "TIMESTAMPTZ";
    /// <inheritdoc />
    public string FeedbackOrderByClause => "created_utc DESC, id DESC";
    /// <inheritdoc />
    public string FeedbackInsertReturningIdSql => """
        INSERT INTO feedback (created_utc, type, message, email, page_url, user_agent, ip_hash, app_version, status)
        VALUES (@created, @type, @message, @email, @pageUrl, @userAgent, @ipHash, @appVersion, @status)
        RETURNING id;
        """;
}
