using DeckFlow.Core.Knowledge;

namespace DeckFlow.Core.Integration;

/// <summary>
/// Final outcome for a transcript fetch attempt.
/// </summary>
public enum TranscriptOutcome
{
    /// <summary>
    /// Transcript text came from upstream captions.
    /// </summary>
    Captions,

    /// <summary>
    /// Transcript text came from Whisper transcription.
    /// </summary>
    Whisper,

    /// <summary>
    /// Transcript fetch or transcription failed.
    /// </summary>
    Failed,

    /// <summary>
    /// Whisper transcription was skipped because the monthly cap would be exceeded.
    /// </summary>
    SkippedOverCap,

    /// <summary>
    /// Transcript fetch was skipped because captions were unavailable and Whisper was disabled.
    /// </summary>
    SkippedNoCaptions,
}

/// <summary>
/// Non-null, status-carrying result from a transcript source.
/// </summary>
public sealed record TranscriptFetchResult
{
    /// <summary>
    /// Outcome discriminator for the transcript attempt.
    /// </summary>
    public required TranscriptOutcome Outcome { get; init; }

    /// <summary>
    /// Transcript body for caption or Whisper success outcomes.
    /// </summary>
    public string? Body { get; init; }

    /// <summary>
    /// Transcript source matching one of the <see cref="TranscriptSource"/> constants.
    /// </summary>
    public string? Source { get; init; }

    /// <summary>
    /// Failure reason for failed outcomes.
    /// </summary>
    public string? FailureReason { get; init; }

    /// <summary>
    /// Indicates whether the caption track was auto-generated when <see cref="Source"/> is captions.
    /// </summary>
    public bool? IsAutoGenerated { get; init; }

    /// <summary>
    /// Whisper seconds billed for a Whisper success outcome.
    /// </summary>
    public int? SecondsBilled { get; init; }

    /// <summary>
    /// Whisper cost in USD for a Whisper success outcome.
    /// </summary>
    public decimal? CostUsd { get; init; }

    /// <summary>
    /// Creates a successful captions result.
    /// </summary>
    /// <param name="body">Caption transcript body.</param>
    /// <param name="isAutoGenerated">Whether the caption track was auto-generated.</param>
    /// <returns>A captions transcript result.</returns>
    public static TranscriptFetchResult FromCaptions(string body, bool isAutoGenerated)
        => new()
        {
            Outcome = TranscriptOutcome.Captions,
            Body = body,
            Source = TranscriptSource.Captions,
            IsAutoGenerated = isAutoGenerated,
        };

    /// <summary>
    /// Creates a successful Whisper result with billing fields.
    /// </summary>
    /// <param name="body">Whisper transcript body.</param>
    /// <param name="secondsBilled">Whisper seconds billed.</param>
    /// <param name="costUsd">Whisper cost in USD.</param>
    /// <returns>A Whisper transcript result.</returns>
    public static TranscriptFetchResult FromWhisper(string body, int secondsBilled, decimal costUsd)
        => new()
        {
            Outcome = TranscriptOutcome.Whisper,
            Body = body,
            Source = TranscriptSource.Whisper,
            SecondsBilled = secondsBilled,
            CostUsd = costUsd,
        };

    /// <summary>
    /// Creates a failed transcript result.
    /// </summary>
    /// <param name="reason">Failure reason.</param>
    /// <returns>A failed transcript result.</returns>
    public static TranscriptFetchResult Failed(string reason)
        => new()
        {
            Outcome = TranscriptOutcome.Failed,
            FailureReason = reason,
        };

    /// <summary>
    /// Creates a skipped-over-cap transcript result.
    /// </summary>
    /// <returns>A skipped-over-cap transcript result.</returns>
    public static TranscriptFetchResult SkippedOverCap()
        => new()
        {
            Outcome = TranscriptOutcome.SkippedOverCap,
        };

    /// <summary>
    /// Creates a skipped-no-captions transcript result.
    /// </summary>
    /// <returns>A skipped-no-captions transcript result.</returns>
    public static TranscriptFetchResult SkippedNoCaptions()
        => new()
        {
            Outcome = TranscriptOutcome.SkippedNoCaptions,
        };
}

/// <summary>
/// Pure transcript source abstraction for content ingestion.
/// </summary>
public interface ITranscriptSource
{
    /// <summary>
    /// Source type identifier matching a <see cref="ContentSourceType"/> constant.
    /// </summary>
    string SourceType { get; }

    /// <summary>
    /// Fetches a transcript for an upstream natural key without persisting anything.
    /// </summary>
    /// <param name="naturalKey">Source-specific natural key, such as a YouTube video id or URL.</param>
    /// <param name="knownDuration">Authoritative video duration from the channel lister when available; passed to the Whisper cap projection, which uses the max of this value and the best-effort audio duration and fails if both are unknown (KB-05).</param>
    /// <param name="monthKey">Verb-supplied yyyy-MM month key used for BOTH the Whisper cap check and the verb's ledger write — must be the same value for both (Codex iter2 MEDIUM).</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A non-null status-carrying transcript result.</returns>
    Task<TranscriptFetchResult> FetchTranscriptAsync(
        string naturalKey,
        TimeSpan? knownDuration,
        string monthKey,
        CancellationToken ct = default);
}
