namespace DeckFlow.Core.Integration;

/// <summary>
/// Fetches YouTube caption text without persisting anything.
/// </summary>
public interface IYouTubeTranscriptFetcher
{
    /// <summary>
    /// Fetches captions for a YouTube video.
    /// </summary>
    /// <param name="videoId">YouTube video id or URL.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A status-carrying caption result.</returns>
    Task<YouTubeCaptionResult> FetchCaptionsAsync(string videoId, CancellationToken ct = default);
}

/// <summary>
/// Status-carrying result for a YouTube caption fetch.
/// </summary>
public sealed record YouTubeCaptionResult
{
    /// <summary>
    /// Indicates whether usable captions were found.
    /// </summary>
    public required bool HasCaptions { get; init; }

    /// <summary>
    /// Joined caption body when captions are available.
    /// </summary>
    public string? Body { get; init; }

    /// <summary>
    /// Indicates whether the selected caption track is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    /// <summary>
    /// Structured caption track kind: auto_generated or manual.
    /// </summary>
    public string? CaptionTrackKind { get; init; }

    /// <summary>
    /// Selected caption language code.
    /// </summary>
    public string? LanguageCode { get; init; }

    /// <summary>
    /// Creates a successful caption result, classifying whitespace as no captions.
    /// </summary>
    /// <param name="body">Joined caption body.</param>
    /// <param name="isAutoGenerated">Whether the selected caption track is auto-generated.</param>
    /// <param name="languageCode">Selected caption language code.</param>
    /// <returns>A caption result, or no captions when the body is empty.</returns>
    public static YouTubeCaptionResult FromCaptions(string? body, bool isAutoGenerated, string? languageCode)
    {
        if (string.IsNullOrWhiteSpace(body))
        {
            return NoCaptions();
        }

        return new YouTubeCaptionResult
        {
            HasCaptions = true,
            Body = body,
            IsAutoGenerated = isAutoGenerated,
            CaptionTrackKind = isAutoGenerated ? "auto_generated" : "manual",
            LanguageCode = languageCode,
        };
    }

    /// <summary>
    /// Creates a no-captions result.
    /// </summary>
    /// <returns>A no-captions result.</returns>
    public static YouTubeCaptionResult NoCaptions()
        => new()
        {
            HasCaptions = false,
        };
}
