using Polly;
using Polly.Retry;
using YoutubeExplode;
using YoutubeExplode.Exceptions;
using YoutubeExplode.Videos.ClosedCaptions;

namespace DeckFlow.Core.Integration;

/// <summary>
/// Fetches YouTube closed captions through YoutubeExplode.
/// </summary>
public sealed class YouTubeTranscriptFetcher : IYouTubeTranscriptFetcher
{
    private static readonly AsyncRetryPolicy RetryPolicy = Policy
        .Handle<HttpRequestException>()
        .Or<TaskCanceledException>()
        .Or<YoutubeExplodeException>()
        .WaitAndRetryAsync(
            retryCount: 6,
            sleepDurationProvider: attempt => TimeSpan.FromSeconds(Math.Pow(2, attempt)) + TimeSpan.FromMilliseconds(Random.Shared.Next(0, 250)),
            onRetry: (exception, timespan, retryAttempt, context) => { });

    private readonly Func<string, CancellationToken, Task<YouTubeCaptionResult>> _executeAsync;

    /// <summary>
    /// Initializes a YouTube caption fetcher with an injected HTTP client.
    /// </summary>
    /// <param name="httpClient">HTTP client used by YoutubeExplode.</param>
    public YouTubeTranscriptFetcher(HttpClient httpClient)
        : this(CreateExecuteAsync(httpClient))
    {
    }

    /// <summary>
    /// Initializes a YouTube caption fetcher with a delegate seam for tests.
    /// </summary>
    /// <param name="executeAsync">Caption fetch delegate.</param>
    internal YouTubeTranscriptFetcher(Func<string, CancellationToken, Task<YouTubeCaptionResult>> executeAsync)
    {
        ArgumentNullException.ThrowIfNull(executeAsync);
        _executeAsync = executeAsync;
    }

    /// <summary>
    /// Fetches captions for a YouTube video id or URL.
    /// </summary>
    /// <param name="videoId">YouTube video id or URL.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>A status-carrying caption result.</returns>
    public Task<YouTubeCaptionResult> FetchCaptionsAsync(string videoId, CancellationToken ct = default)
        => _executeAsync(videoId, ct);

    internal static string FormatTimestampedCaption(string text, TimeSpan offset)
        => $"[{(int)offset.TotalMinutes:D2}:{offset.Seconds:D2}] {text}";

    private static Func<string, CancellationToken, Task<YouTubeCaptionResult>> CreateExecuteAsync(HttpClient httpClient)
    {
        ArgumentNullException.ThrowIfNull(httpClient);
        var youtube = new YoutubeClient(httpClient);

        return (videoId, ct) => RetryPolicy.ExecuteAsync(
            token => FetchWithClientAsync(youtube, videoId, token),
            ct);
    }

    private static async Task<YouTubeCaptionResult> FetchWithClientAsync(
        YoutubeClient youtube,
        string videoId,
        CancellationToken ct)
    {
        var manifest = await youtube.Videos.ClosedCaptions.GetManifestAsync(videoId, ct).ConfigureAwait(false);
        if (manifest.Tracks.Count == 0)
        {
            return YouTubeCaptionResult.NoCaptions();
        }

        var trackInfo = SelectCaptionTrack(manifest);
        var track = await youtube.Videos.ClosedCaptions.GetAsync(trackInfo, ct).ConfigureAwait(false);
        var body = string.Join("\n", track.Captions.Select(caption => FormatTimestampedCaption(caption.Text, caption.Offset)));

        return YouTubeCaptionResult.FromCaptions(body, trackInfo.IsAutoGenerated, trackInfo.Language.Code);
    }

    private static ClosedCaptionTrackInfo SelectCaptionTrack(ClosedCaptionManifest manifest)
        => manifest.TryGetByLanguage("en-US")
            ?? manifest.TryGetByLanguage("en")
            ?? manifest.Tracks.FirstOrDefault(track => track.Language.Code.StartsWith("en", StringComparison.OrdinalIgnoreCase))
            ?? manifest.Tracks[0];
}
