using DeckFlow.Core.Knowledge;

namespace DeckFlow.Core.Integration;

/// <summary>
/// Pure YouTube transcript source composing captions first, then Whisper fallback.
/// </summary>
public sealed class YouTubeTranscriptSource : ITranscriptSource
{
    private readonly IYouTubeTranscriptFetcher _fetcher;
    private readonly IYouTubeAudioSource _audioSource;
    private readonly IWhisperTranscriptionService _whisper;

    /// <summary>
    /// Initializes a YouTube transcript source.
    /// </summary>
    /// <param name="fetcher">Caption fetcher.</param>
    /// <param name="audioSource">Audio download source for Whisper fallback.</param>
    /// <param name="whisper">Whisper transcription fallback.</param>
    public YouTubeTranscriptSource(
        IYouTubeTranscriptFetcher fetcher,
        IYouTubeAudioSource audioSource,
        IWhisperTranscriptionService whisper)
    {
        ArgumentNullException.ThrowIfNull(fetcher);
        ArgumentNullException.ThrowIfNull(audioSource);
        ArgumentNullException.ThrowIfNull(whisper);
        _fetcher = fetcher;
        _audioSource = audioSource;
        _whisper = whisper;
    }

    /// <inheritdoc />
    public string SourceType => ContentSourceType.Youtube;

    /// <inheritdoc />
    public async Task<TranscriptFetchResult> FetchTranscriptAsync(
        string naturalKey,
        TimeSpan? knownDuration,
        string monthKey,
        CancellationToken ct = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(naturalKey);
        ArgumentException.ThrowIfNullOrWhiteSpace(monthKey);

        var captions = await _fetcher.FetchCaptionsAsync(naturalKey, ct).ConfigureAwait(false);
        if (captions.HasCaptions)
        {
            return TranscriptFetchResult.FromCaptions(captions.Body!, captions.IsAutoGenerated);
        }

        using var audio = await _audioSource.DownloadAudioAsync(naturalKey, ct).ConfigureAwait(false);
        var whisperResult = await _whisper.TranscribeAsync(audio, knownDuration, monthKey, ct).ConfigureAwait(false);
        return MapWhisperResult(whisperResult);
    }

    private static TranscriptFetchResult MapWhisperResult(WhisperTranscriptionResult result)
        => result.Outcome switch
        {
            TranscriptOutcome.Whisper => TranscriptFetchResult.FromWhisper(
                result.Body!,
                result.SecondsBilled,
                result.CostUsd),
            TranscriptOutcome.SkippedOverCap => TranscriptFetchResult.SkippedOverCap(),
            TranscriptOutcome.Failed => TranscriptFetchResult.Failed(result.FailureReason ?? "whisper failed"),
            _ => TranscriptFetchResult.Failed($"unsupported Whisper outcome: {result.Outcome}"),
        };
}
