using DeckFlow.Core.Integration;
using DeckFlow.Core.Knowledge;
using Xunit;

namespace DeckFlow.Core.Tests;

/// <summary>
/// Tests for transcript fetch result factory helpers.
/// </summary>
public sealed class TranscriptFetchResultTests
{
    [Fact]
    public void FromCaptions_CarriesCaptionOutcomeAndTrackKind()
    {
        var result = TranscriptFetchResult.FromCaptions("caption body", true);

        Assert.Equal(TranscriptOutcome.Captions, result.Outcome);
        Assert.Equal("caption body", result.Body);
        Assert.Equal(TranscriptSource.Captions, result.Source);
        Assert.True(result.IsAutoGenerated);
        Assert.Null(result.SecondsBilled);
        Assert.Null(result.CostUsd);
    }

    [Fact]
    public void FromWhisper_CarriesBillingFields()
    {
        var result = TranscriptFetchResult.FromWhisper("whisper body", 123, 0.0123m);

        Assert.Equal(TranscriptOutcome.Whisper, result.Outcome);
        Assert.Equal("whisper body", result.Body);
        Assert.Equal(TranscriptSource.Whisper, result.Source);
        Assert.Null(result.IsAutoGenerated);
        Assert.Equal(123, result.SecondsBilled);
        Assert.Equal(0.0123m, result.CostUsd);
    }

    [Fact]
    public void SkippedOverCap_RemainsDistinctFromFailed()
    {
        var result = TranscriptFetchResult.SkippedOverCap();

        Assert.Equal(TranscriptOutcome.SkippedOverCap, result.Outcome);
        Assert.Null(result.Body);
        Assert.Null(result.Source);
        Assert.Null(result.FailureReason);
    }

    [Fact]
    public void SkippedNoCaptions_RemainsDistinctFromFailedWithoutBilling()
    {
        var result = TranscriptFetchResult.SkippedNoCaptions();

        Assert.Equal(TranscriptOutcome.SkippedNoCaptions, result.Outcome);
        Assert.Null(result.Body);
        Assert.Null(result.Source);
        Assert.Null(result.FailureReason);
        Assert.Null(result.SecondsBilled);
        Assert.Null(result.CostUsd);
    }
}
