using DeckFlow.Core.Integration;
using Xunit;

namespace DeckFlow.Core.Tests;

/// <summary>
/// Tests for the YouTube caption fetcher delegate seam and result classification.
/// </summary>
public sealed class YouTubeTranscriptFetcherTests
{
    [Fact]
    public void FormatTimestampedCaption_UsesTotalMinutesAndZeroPaddedSeconds()
    {
        Assert.Equal(
            "[01:05] hello",
            YouTubeTranscriptFetcher.FormatTimestampedCaption("hello", TimeSpan.FromSeconds(65)));
        Assert.Equal(
            "[65:07] long video",
            YouTubeTranscriptFetcher.FormatTimestampedCaption("long video", TimeSpan.FromHours(1) + TimeSpan.FromMinutes(5) + TimeSpan.FromSeconds(7)));
    }

    [Fact]
    public async Task FetchCaptionsAsync_ReturnsJoinedCaptionBody()
    {
        var fetcher = new YouTubeTranscriptFetcher((videoId, ct) =>
        {
            Assert.Equal("video-1", videoId);
            return Task.FromResult(YouTubeCaptionResult.FromCaptions("first caption second caption", false, "en"));
        });

        var result = await fetcher.FetchCaptionsAsync("video-1");

        Assert.True(result.HasCaptions);
        Assert.Equal("first caption second caption", result.Body);
        Assert.False(result.IsAutoGenerated);
        Assert.Equal("manual", result.CaptionTrackKind);
        Assert.Equal("en", result.LanguageCode);
    }

    [Fact]
    public async Task FetchCaptionsAsync_NoCaptionsReturnsStatusResult()
    {
        var fetcher = new YouTubeTranscriptFetcher((videoId, ct) =>
            Task.FromResult(YouTubeCaptionResult.NoCaptions()));

        var result = await fetcher.FetchCaptionsAsync("video-2");

        Assert.False(result.HasCaptions);
        Assert.Null(result.Body);
        Assert.Null(result.CaptionTrackKind);
    }

    [Fact]
    public async Task FetchCaptionsAsync_AutoGeneratedTrackIsAccepted()
    {
        var fetcher = new YouTubeTranscriptFetcher((videoId, ct) =>
            Task.FromResult(YouTubeCaptionResult.FromCaptions("auto captions", true, "en-US")));

        var result = await fetcher.FetchCaptionsAsync("video-3");

        Assert.True(result.HasCaptions);
        Assert.True(result.IsAutoGenerated);
        Assert.Equal("auto_generated", result.CaptionTrackKind);
        Assert.Equal("auto captions", result.Body);
    }

    [Fact]
    public async Task FetchCaptionsAsync_EmptyCaptionBodyReturnsNoCaptions()
    {
        var fetcher = new YouTubeTranscriptFetcher((videoId, ct) =>
            Task.FromResult(YouTubeCaptionResult.FromCaptions(" \t\r\n ", true, "en")));

        var result = await fetcher.FetchCaptionsAsync("video-4");

        Assert.False(result.HasCaptions);
        Assert.Null(result.Body);
        Assert.False(result.IsAutoGenerated);
        Assert.Null(result.LanguageCode);
    }
}
