using DeckFlow.Core.Integration;
using Xunit;

namespace DeckFlow.Core.Tests;

/// <summary>
/// Tests for the pure YouTube transcript source composition.
/// </summary>
public sealed class YouTubeTranscriptSourceTests
{
    [Fact]
    public async Task FetchTranscriptAsync_CaptionsPresentReturnsCaptionsWithoutAudioOrWhisper()
    {
        var fetcher = new FakeYouTubeTranscriptFetcher(YouTubeCaptionResult.FromCaptions("caption body", false, "en"));
        var audioSource = new FakeYouTubeAudioSource();
        var whisper = new FakeWhisperTranscriptionService();
        var source = new YouTubeTranscriptSource(fetcher, audioSource, whisper, whisperEnabled: false);

        var result = await source.FetchTranscriptAsync("video-1", TimeSpan.FromMinutes(12), "2026-05");

        Assert.Equal(TranscriptOutcome.Captions, result.Outcome);
        Assert.Equal("caption body", result.Body);
        Assert.Equal("captions", result.Source);
        Assert.False(result.IsAutoGenerated);
        Assert.Equal(1, fetcher.Calls);
        Assert.Equal(0, audioSource.Calls);
        Assert.Equal(0, whisper.Calls);
    }

    [Fact]
    public async Task FetchTranscriptAsync_NoCaptionsWhisperSuccessSurfacesBillingAndForwardsDurationAndMonthKey()
    {
        var audio = CreateAudio();
        var knownDuration = TimeSpan.FromMinutes(37);
        var fetcher = new FakeYouTubeTranscriptFetcher(YouTubeCaptionResult.NoCaptions());
        var audioSource = new FakeYouTubeAudioSource(audio);
        var whisper = new FakeWhisperTranscriptionService
        {
            Result = new WhisperTranscriptionResult
            {
                Outcome = TranscriptOutcome.Whisper,
                Body = "whisper body",
                SecondsBilled = 222,
                CostUsd = 0.0222m,
                MonthKey = "2026-05",
            },
        };
        var source = new YouTubeTranscriptSource(fetcher, audioSource, whisper, whisperEnabled: true);

        var result = await source.FetchTranscriptAsync("video-2", knownDuration, "2026-05");

        Assert.Equal(TranscriptOutcome.Whisper, result.Outcome);
        Assert.Equal("whisper body", result.Body);
        Assert.Equal("whisper", result.Source);
        Assert.Equal(222, result.SecondsBilled);
        Assert.Equal(0.0222m, result.CostUsd);
        Assert.Equal(knownDuration, whisper.LastKnownDuration);
        Assert.Equal("2026-05", whisper.LastMonthKey);
        Assert.False(File.Exists(audio.TempFilePath));
    }

    [Fact]
    public async Task FetchTranscriptAsync_NoCaptionsWithWhisperDisabledSkipsWithoutAudioOrWhisper()
    {
        var fetcher = new FakeYouTubeTranscriptFetcher(YouTubeCaptionResult.NoCaptions());
        var audioSource = new FakeYouTubeAudioSource();
        var whisper = new FakeWhisperTranscriptionService();
        var source = new YouTubeTranscriptSource(fetcher, audioSource, whisper, whisperEnabled: false);

        var result = await source.FetchTranscriptAsync("video-no-captions", TimeSpan.FromMinutes(8), "2026-05");

        Assert.Equal(TranscriptOutcome.SkippedNoCaptions, result.Outcome);
        Assert.Null(result.Body);
        Assert.Null(result.Source);
        Assert.Null(result.SecondsBilled);
        Assert.Null(result.CostUsd);
        Assert.Equal(1, fetcher.Calls);
        Assert.Equal(0, audioSource.Calls);
        Assert.Equal(0, whisper.Calls);
    }

    [Fact]
    public async Task FetchTranscriptAsync_NoCaptionsSkippedOverCapStaysDistinctFromFailed()
    {
        var fetcher = new FakeYouTubeTranscriptFetcher(YouTubeCaptionResult.NoCaptions());
        var audioSource = new FakeYouTubeAudioSource(CreateAudio());
        var whisper = new FakeWhisperTranscriptionService
        {
            Result = new WhisperTranscriptionResult
            {
                Outcome = TranscriptOutcome.SkippedOverCap,
                MonthKey = "2026-05",
            },
        };
        var source = new YouTubeTranscriptSource(fetcher, audioSource, whisper, whisperEnabled: true);

        var result = await source.FetchTranscriptAsync("video-3", TimeSpan.FromMinutes(3), "2026-05");

        Assert.Equal(TranscriptOutcome.SkippedOverCap, result.Outcome);
        Assert.NotEqual(TranscriptOutcome.Failed, result.Outcome);
        Assert.Null(result.Body);
        Assert.Null(result.Source);
    }

    [Fact]
    public async Task FetchTranscriptAsync_NoCaptionsFailedReturnsFailureReason()
    {
        var fetcher = new FakeYouTubeTranscriptFetcher(YouTubeCaptionResult.NoCaptions());
        var audioSource = new FakeYouTubeAudioSource(CreateAudio());
        var whisper = new FakeWhisperTranscriptionService
        {
            Result = new WhisperTranscriptionResult
            {
                Outcome = TranscriptOutcome.Failed,
                FailureReason = "ffmpeg not available",
                MonthKey = "2026-05",
            },
        };
        var source = new YouTubeTranscriptSource(fetcher, audioSource, whisper, whisperEnabled: true);

        var result = await source.FetchTranscriptAsync("video-4", TimeSpan.FromMinutes(4), "2026-05");

        Assert.Equal(TranscriptOutcome.Failed, result.Outcome);
        Assert.Equal("ffmpeg not available", result.FailureReason);
        Assert.Null(result.Body);
        Assert.Null(result.Source);
    }

    private static AudioDownloadResult CreateAudio()
    {
        var tempDir = Path.Combine(Path.GetTempPath(), "deckflow-audio", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(tempDir);
        var tempPath = Path.Combine(tempDir, "audio.webm");
        File.WriteAllText(tempPath, "audio");
        return new AudioDownloadResult
        {
            TempFilePath = tempPath,
            FileName = "audio.webm",
            SizeBytes = 123,
            DurationSeconds = 0,
        };
    }

    private sealed class FakeYouTubeTranscriptFetcher : IYouTubeTranscriptFetcher
    {
        private readonly YouTubeCaptionResult _result;

        public FakeYouTubeTranscriptFetcher(YouTubeCaptionResult result)
        {
            _result = result;
        }

        public int Calls { get; private set; }

        public Task<YouTubeCaptionResult> FetchCaptionsAsync(string videoId, CancellationToken ct = default)
        {
            Calls++;
            return Task.FromResult(_result);
        }
    }

    private sealed class FakeYouTubeAudioSource : IYouTubeAudioSource
    {
        private readonly AudioDownloadResult? _result;

        public FakeYouTubeAudioSource(AudioDownloadResult? result = null)
        {
            _result = result;
        }

        public int Calls { get; private set; }

        public Task<AudioDownloadResult> DownloadAudioAsync(string videoUrlOrId, CancellationToken ct = default)
        {
            Calls++;
            return Task.FromResult(_result ?? CreateAudio());
        }
    }

    private sealed class FakeWhisperTranscriptionService : IWhisperTranscriptionService
    {
        public WhisperTranscriptionResult Result { get; init; } = new()
        {
            Outcome = TranscriptOutcome.Failed,
            FailureReason = "not configured",
            MonthKey = "2026-05",
        };

        public int Calls { get; private set; }

        public TimeSpan? LastKnownDuration { get; private set; }

        public string? LastMonthKey { get; private set; }

        public Task<WhisperTranscriptionResult> TranscribeAsync(
            AudioDownloadResult audio,
            TimeSpan? knownDuration,
            string monthKey,
            CancellationToken ct = default)
        {
            Calls++;
            LastKnownDuration = knownDuration;
            LastMonthKey = monthKey;
            return Task.FromResult(Result);
        }
    }

}
