namespace DeckFlow.Core.Knowledge;

/// <summary>
/// Immutable model for a Whisper transcription spend ledger entry.
/// </summary>
public sealed record WhisperSpendEntry
{
    /// <summary>Surrogate identifier for the spend ledger row.</summary>
    public required long Id { get; init; }

    /// <summary>Identifier of the content item billed for transcription.</summary>
    public required long VideoId { get; init; }

    /// <summary>Number of audio seconds billed by the transcription provider.</summary>
    public required int SecondsBilled { get; init; }

    /// <summary>Cost in USD recorded for the billed transcription work.</summary>
    public required decimal CostUsd { get; init; }

    /// <summary>UTC month key in <c>YYYY-MM</c> format used for cap checks.</summary>
    public required string MonthKey { get; init; }

    /// <summary>UTC timestamp when the spend ledger row was created.</summary>
    public required DateTimeOffset CreatedUtc { get; init; }
}

/// <summary>
/// Immutable model for a local content harvest run summary.
/// </summary>
public sealed record ContentHarvestRun
{
    /// <summary>Surrogate identifier for the harvest run row.</summary>
    public required long Id { get; init; }

    /// <summary>UTC timestamp when the harvest run started.</summary>
    public required DateTimeOffset StartedUtc { get; init; }

    /// <summary>UTC timestamp when the harvest run completed, or <see langword="null"/> while running.</summary>
    public DateTimeOffset? CompletedUtc { get; init; }

    /// <summary>Number of sources processed by the harvest run.</summary>
    public required int SourcesProcessed { get; init; }

    /// <summary>Number of content items processed by the harvest run.</summary>
    public required int VideosProcessed { get; init; }

    /// <summary>Number of transcripts fetched or generated by the harvest run.</summary>
    public required int TranscriptsFetched { get; init; }

    /// <summary>Number of Whisper transcription calls made by the harvest run.</summary>
    public required int WhisperCalls { get; init; }

    /// <summary>Total USD transcription spend recorded during the harvest run.</summary>
    public required decimal SpendUsd { get; init; }

    /// <summary>Reason the harvest run aborted, or <see langword="null"/> when it completed normally.</summary>
    public string? AbortedReason { get; init; }
}
